[build]
  base = "texas_proud_mowing/texas-proud-mowing"  # Relative path to the root of your project
  publish = "texas_proud_mowing/texas-proud-mowing/build"  # Path to your build output directory
  command = "npm run build"  # The command to build your project

[context.production.environment]
  NODE_ENV = "production"

[context.split-tests]
  command = "npm run test"  # Command to run split tests

[context.deploy-preview]
  command = "npm run build"  # Command for deploy previews

[context.branch-deploy]
  command = "npm run build"  # Command for branch deploys

[context.next.environment]
  NODE_ENV = "production"

[build.environment]
  NODE_ENV = "production"
